server:
  port: 8081
spring:
  application:
    name: boot-1
  zipkin:
    base-url: http://localhost:6060
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
