eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
server:
  port: 6060
spring:
  application:
    name: zipkin
management:
  metrics:
    web:
      server:
        auto-time-requests: false
