spring:
  application:
    name: consumer-2
  zipkin:
    base-url: http://localhost:6060
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  hystrix:
    enabled: true
